services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: iot-postgres-prod
    environment:
      POSTGRES_DB: invernadero_iot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - iot-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: iot-redis-prod
    command: redis-server --requirepass redis123 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data_prod:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - iot-network

  # Database Initialization (runs once)
  db-init:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    container_name: iot-db-init-prod
    environment:
      NODE_ENV: production
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABASE: invernadero_iot
      PG_USER: postgres
      PG_PASSWORD: postgres123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["node", "docker-init-simple.js"]
    restart: "no"
    networks:
      - iot-network

  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    container_name: iot-app-prod
    ports:
      - "4001:4001"
    environment:
      NODE_ENV: production
      PORT: 4001
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABASE: invernadero_iot
      PG_USER: postgres
      PG_PASSWORD: postgres123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
      MQTT_HOST: sdb201a6.ala.us-east-1.emqxsl.com
      MQTT_PORT: 8883
      MQTT_USERNAME: Backend
      MQTT_PASSWORD: 11211121
      MQTT_BROKER_URL: mqtts://Backend:11211121@sdb201a6.ala.us-east-1.emqxsl.com:8883
      JWT_SECRET: super_secret_jwt_key_for_local_development_only_32_chars
      ACCESS_TOKEN_SECRET: access_token_secret_for_local_dev_different_from_jwt
      REFRESH_TOKEN_SECRET: refresh_token_secret_for_local_dev_unique_value
      BCRYPT_ROUNDS: 10
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173
      GRAPHQL_INTROSPECTION: "true"
      GRAPHQL_PLAYGROUND: "true"
      GRAPHQL_DEBUG: "true"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - iot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Data Seeder (runs once to populate test data)
  data-seeder:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    container_name: iot-data-seeder-prod
    environment:
      NODE_ENV: production
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABASE: invernadero_iot
      PG_USER: postgres
      PG_PASSWORD: postgres123
    depends_on:
      app:
        condition: service_healthy
    command: ["node", "insert-test-data.js"]
    restart: "no"
    networks:
      - iot-network

volumes:
  postgres_data_prod:
  redis_data_prod:

networks:
  iot-network:
    driver: bridge