services:
  # Solo PostgreSQL y Redis
  postgres:
    image: postgres:14-alpine
    container_name: iot-postgres-simple
    environment:
      POSTGRES_DB: invernadero_iot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_simple:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: iot-redis-simple
    command: redis-server --requirepass redis123 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data_simple:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 15s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data_simple:
  redis_data_simple: